<template>
  <div>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
    <li>sdfdsfsd</li>
  </div>
</template>
<script>
export default {
  name: 'CartListItem',
  props: {
    product: {
      type: Object,
      default() {
        return {}
      }
    }
  }
}
</script>
<style scoped>
</style>